spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?userUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 3edc$RFV!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
