# 服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 应用服务端口
server:
  port: 5000
spring:
  # 应用名称
  application:
    name: CaaS_Sleuth_Gateway
  # Sleuth配置：100%
  sleuth:
    sampler:
      percentage: 1.0
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# 服务网关配置
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: CaaS_Sleuth_User
